### ISSUE TITLE
How to include native python packages like gevent with build

### ISSUE THREAD

**Issue by canewsin** [GRRedWings/python3-android#22]
How to build Python Packages into site-packages after Python build

**Comment by GRRedWings** [comment]
I did not originate this project, I've mostly been maintaining my fork for my needs.  With that I have no had to add any packages, but I have had to update some.  

If you look at the build_deps.py file (https://github.com/GRRedWings/python3-android/blob/master/Android/build_deps.py), I would start here and follow the same pattern as the other libraries being built here.
