### ISSUE TITLE
Error on Copying /build Files

### ISSUE THREAD

**Issue by ZongyuanLu** [GRRedWings/python3-android#31]
Hi, there is an issue while copying all /build files into /data/local/tmp.
![image](https://user-images.githubusercontent.com/48280814/202385879-8ec62aa7-ecc1-4a8e-9a3d-e480a01f168d.png)
As pic shows, the copying operation failed with "Permission denied". To solve this problem, I rooted my phone and found "adb root" works.
So I wonder that whether my Android device must be rooted or not. If not, could u tell me how to solve the "Permission denied" problem? thx.

**Comment by ZongyuanLu** [comment]
Additinally, I cannot even push files in /build to /sdcard, this copying operation is still prohibited with "Permission denied".

**Comment by GRRedWings** [comment]
The project has an example of how I use it on Android.  I build the library and embed it in my application and call it through JNI.  I have never used or had to use adb commands to run Python on a device.

**Comment by ZongyuanLu** [comment]
Thanks for your reply, Brian.  I will build the "AndroidApp" directory and try again, have a nice day!

**Comment by ZongyuanLu** [comment]
Hi, I have used the AndroidApp in this project. What confuses me is only basic Python modules such as _os_, _time_ and _sys_ work well. Is there any way to use other Python modules (e.g. _json_, _socket_ and _collections_) in this project? Thanks.

**Comment by GRRedWings** [comment]
I'm not sure what you mean by work well.  I use all of your examples myself with this build of Python.  Can you give more detail about what problems you are having?

**Comment by ZongyuanLu** [comment]
Sorry for my ambiguous expressions, I have found that I forgot to add __android.permission.INTERNET__ in my Android App, so that the __socket__ module could not work (e.g. Python thread was killed). It is a rookie-like mistake which makes me embarassed. Calling Python library by JNI is awesome and deserves a star, thanks a lot!
