### ISSUE TITLE
Help.....

### ISSUE THREAD

**Issue by WickyHuang** [GRRedWings/python3-android#39]
The compilation was successful, but there are exceptions during runtime. There are issues with dynamic libraries when importing modules.

 import math
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/local/tmp/build/usr/lib/python3.12/lib-dynload/math.cpython-312.so"...

![image](https://github.com/GRRedWings/python3-android/assets/49517263/978a1c60-5fbf-4ee6-8c7a-42c9a20ca08c)

lf -s /data/local/tmp/build/usr/lib/python3.12/lib-dynload/math.cpython-312.so |grep PyExc_ValueError                                <
    10: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND PyExc_ValueError
   203: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND PyExc_ValueError

**Comment by WickyHuang** [comment]
ARCH="arm64"
ANDROID_API="29"
PYVER=3.12.1

some args: --enable-shared --without-ensurepip --enable-ipv6 --with-build-python

**Comment by GRRedWings** [comment]
Are you trying to build Python 3.12 with the script?  Python 3.12 has issues. There is a branch where I got it working, but I have not had time to work on this, and I was holding off on merging the master branch to run 3.12 until it was stable.

**Comment by WickyHuang** [comment]
I manually tweaked the issue with the patch and it worked successfully, awesome thanks

**Comment by FeodorFitsner** [comment]
what was the patch?

**Comment by GRRedWings** [comment]
@FeodorFitsner - There is a patch file in the 3.12 branch.  That branch is setup to apply the patch and build.

**Comment by FeodorFitsner** [comment]
@GRRedWings sorry I couldn't found `3.12` branch. Could you share a link to it please?

**Comment by nverbeek** [comment]
@FeodorFitsner I believe the branch you're looking for is [API26-Build](https://github.com/GRRedWings/python3-android/tree/API26-Build)
