### ISSUE TITLE
can this scripts support python 3.6 ?

### ISSUE THREAD

**Issue by JohnSuuAries** [GRRedWings/python3-android#4]

**Comment by GRRedWings** [comment]
This project is not updated to the newer versions of Python.  I'm currently trying to figure out how to update to the latest NDK without gcc. I'm not sure if Python 3.6 is in my plans anytime soon.

**Comment by GRRedWings** [comment]
I've been working on 3.7.  It all builds, but I'm having issues with Bzip and ctypes ATM.

**Comment by GRRedWings** [comment]
This is pretty old, we have moved past 3.6
