### ISSUE TITLE
Spelling: if ( test ! -d $(PREFIX)/inclue ) ; then mkdir -p $(PREFIX)/include ; fi

### ISSUE THREAD

**Issue by noloader** [GRRedWings/python3-android#9]
https://github.com/GRRedWings/python3-android/blob/bae0eb629611437a673b101e2a447025a09acf59/mk/bzip2/1.0.6/bzip2-1.0.6-makefile-env.patch#L56

I believe that should be `include`, not `inclue`.

(Sorry about the issue report. I wanted to leave an inline comment, but the option was not available).

**Comment by GRRedWings** [comment]
good catch, thanks!
